name: Release Edge 🚀

on:
  push:
    branches:
      - 'edge'

jobs:
  release-edge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci

      - name: Get releases
        id: fetch-latest-release
        uses: ./.github/actions/fetch-latest-release
        with:
          github_token: ${{ github.token }}

      - name: Calculate edge version
        id: calculate-edge-version
        uses: ./.github/actions/calculate-edge-version
        with:
          version: ${{ steps.fetch-latest-release.outputs.tag_name }}

      - run: Next version will be ${{ steps.calculate-edge-version.outputs.next-edge }}

      - name: Release PR
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          release-as: ${{ steps.calculate-edge-version.outputs.next-edge }}

      - uses: ./.github/actions/publish
        with:
          tag: edge
        if: ${{ steps.release.outputs.release_created }}
        # ^^ publish only when a new release is created

  # notify:
  #   runs-on: ubuntu-latest
  #   needs: ['release']
  #   if: always() && needs.release.result == 'success'
  #   steps:
  #     - name: Slack Notification - Deployment Success
  #       uses: rtCamp/action-slack-notify@v2.2.0
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #         SLACK_CHANNEL: 'widgets-releases'
  #         SLACK_COLOR: ${{ job.status }}
  #         SLACK_TITLE: 'Deployment succeeded'
  #         SLACK_MESSAGE: 'Success :rocket: cloudinary-video-player version ${{ github.event.inputs.package_version }} deployed successfully'
